export const Data = [
  {
    headingText: "Allergy Check",
    headingNum: "255",
    itemOne: "10 treatments ",
    itemTwo: "",
    itemThree: " Consultation ",
    itemFour: "  Treatments  ",
    itemFiv: " 10 Procedures ",
    itemSix: "",
    itemSeven: " Test Results ",
    btn: "Get Now",
  },
  {
    headingText: "Eye Checkup",
    headingNum: "108",
    itemOne: "3 treatments ",
    itemTwo: "",
    itemThree: "  Refraction  ",
    itemFour: "   Retinal Examination   ",
    itemFiv: "  External Examination  ",
    itemSix: "",
    itemSeven: " Full Closure ",
    btn: "Get Now",
  },
  {
    headingText: "Dental Care",
    headingNum: "320",
    itemOne: "6 treatments ",
    itemTwo: "",
    itemThree: "   Gum Care  ",
    itemFour: "  Consultation   ",
    itemFiv: "   Treatments ",
    itemSix: "",
    itemSeven: " Full Closure ",
    btn: "Get Now",
  },
];
